# Generated by Django 4.2.7 on 2023-12-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
                ('borrowed_on', models.DateTimeField(auto_now_add=True)),
                ('return_on', models.DateTimeField(auto_now=True)),
                ('shelves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.shelves')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
