# Generated by Django 4.2.7 on 2023-12-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelves',
            name='shelf_number',
            field=models.IntegerField(null=True),
        ),
    ]
