# Generated by Django 4.2.7 on 2023-12-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_shelves_shelf_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='shelves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.shelves'),
        ),
    ]
