# Generated by Django 4.2.7 on 2023-12-22 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_books_shelves'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('book_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='shelves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.shelves'),
        ),
    ]
