# Generated by Django 4.2.7 on 2023-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_books_managers_alter_books_shelves'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='written',
            field=models.DateField(blank=True, null=True),
        ),
    ]
