# Generated by Django 4.2.7 on 2023-12-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_books_category_books_number_of_pages_books_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='fun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
