# Generated by Django 4.2.7 on 2023-12-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_books_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='borrowed_on',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.RemoveField(
            model_name='books',
            name='fun',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='number_of_pages',
        ),
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
        migrations.RemoveField(
            model_name='books',
            name='return_on',
        ),
        migrations.RemoveField(
            model_name='books',
            name='shelves',
        ),
        migrations.RemoveField(
            model_name='books',
            name='written',
        ),
        migrations.AddField(
            model_name='books',
            name='shelf',
            field=models.IntegerField(null=True),
        ),
    ]
