# Generated by Django 4.2.7 on 2023-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_alter_books_options_remove_books_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='borrowed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('frt', 'fairy tale'), ('fts', 'fantasy'), ('crm', 'crime'), ('hr', 'horror'), ('fcn', 'fiction')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='return_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='written',
            field=models.DateField(null=True),
        ),
    ]
