# Generated by Django 4.2.7 on 2023-12-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_books_author_books_borrowed_on_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fairy tale', 'frt'), ('fantasy', 'fts'), ('crime', 'crm'), ('horror', 'hr'), ('fiction', 'fcn')], max_length=10, null=True),
        ),
    ]
