# Generated by Django 4.2.7 on 2023-12-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('frt', 'fairy tale'), ('fts', 'fantasy'), ('crm,', 'crime'), ('hrr', 'horror'), ('fcn', 'fiction')], max_length=10, null=True),
        ),
    ]
