# Generated by Django 4.2.7 on 2023-12-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0014_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-name']},
        ),
    ]
